### ISSUE TITLE
Complete example? 

### ISSUE THREAD

**Issue by dfms** [maartene/InkSwift#1]
Hello. Would a simple but complete example – with all the functions applied – be possible in order to understand them better? Thanks a lot. David.

Supported features
==============
- Loading Ink stories loadStory(json: String);
- Basic flow: continue story continueStory() and choices chooseChoiceIndex(_ index: Int);
- Moving to knots/stitches moveToKnitStitch(_ knot: String, stitch: String? = nil);
- Tag support. Read currentTags variable;
- Setting and getting variable values (supports strings, 32-bit integers and doubles);
- Loading and saving state stateToJSON() and loadState(_ jsonDataString: String);
- Combine integration (subscribe to state changes, observe variables).

**Comment by maartene** [comment]
I think so. Note: I have a [repo](https://github.com/maartene/VisualNovel) that uses InkSwift for a basic visual novel implementation. Is something like that what you mean? 

If so, I'll add a link to the repo in the README.

**Comment by maartene** [comment]
Wow, this has been ages.

Anyway, I've also created two very bare-bones implementations for SwiftUI (iOS):
https://github.com/maartene/InkSwiftiOSExample

and command line (Mac/Linux):
https://github.com/maartene/InkSwiftCommandLineExample

Hope this helps!

Note: I'll close this issue after I've also updated the READMEs to point to these examples.
